"""Cria tabela de missoes

Revision ID: 9c9f8aa80401
Revises: a30022a9d50b
Create Date: 2026-08-09 16:39:22.333428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c9f8aa80401'
down_revision = 'a30022a9d50b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('missao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('heroi_id', sa.Integer(), nullable=False),
    sa.Column('ameaca_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('EM_ANDAMENTO', 'CONCLUIDA', 'CANCELADA', name='statusmissao'), nullable=False),
    sa.Column('iniciada_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finalizada_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ameaca_id'], ['ameaca.id'], ),
    sa.ForeignKeyConstraint(['heroi_id'], ['heroi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('missao')
    # ### end Alembic commands ###
