"""Cria tabela de ameacas

Revision ID: a30022a9d50b
Revises: ee61815d60d0
Create Date: 2026-08-08 16:01:06.055366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a30022a9d50b'
down_revision = 'ee61815d60d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ameaca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('nivel', sa.Enum('C', 'B', 'A', 'S', name='nivelameaca'), nullable=False),
    sa.Column('status', sa.Enum('REGISTRADA', 'EM_ATENTIMENTO', 'RESOLVIDA', 'CANCELADA', name='statusameaca'), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ameaca')
    # ### end Alembic commands ###
