"""Cria tabela de herois

Revision ID: ee61815d60d0
Revises: 0afacbb21eab
Create Date: 2026-08-07 19:05:17.700561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee61815d60d0'
down_revision = '0afacbb21eab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heroi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('codinome', sa.String(length=120), nullable=False),
    sa.Column('rank', sa.Enum('C', 'B', 'A', 'S', name='rankheroi'), nullable=False),
    sa.Column('status', sa.Enum('DISPONIVEL', 'EM_MISSAO', 'INATIVO', name='statusheroi'), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codinome'),
    sa.UniqueConstraint('nome')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('heroi')
    # ### end Alembic commands ###
